import Foundation

struct DroneVideo: Sendable {
    let id: Int
    let caption: String
    private var base: String { "https://videos.pjloury.com/video-\(String(format: "%02d", id))" }
    var desktopURL: URL { URL(string: "\(base).mp4")! }
    var mobileURL:  URL { URL(string: "\(base)-mobile.mp4")! }
}

enum VideoPlaylist {
    static let all: [DroneVideo] = [
        DroneVideo(id: 2,  caption: "Good Morning Stanford"),
        DroneVideo(id: 3,  caption: "Snowy Tahoe Treetops"),
        DroneVideo(id: 4,  caption: "Carmel Waves at Dusk"),
        DroneVideo(id: 5,  caption: "Financial District"),
        DroneVideo(id: 6,  caption: "Heavenly Palo Alto"),
        DroneVideo(id: 7,  caption: "Telegraph Hill"),
        DroneVideo(id: 8,  caption: "Stanford Sunset"),
        DroneVideo(id: 10, caption: "Los Altos Hills"),
        DroneVideo(id: 11, caption: "Sterling Vineyard"),
        DroneVideo(id: 12, caption: "Washington Square, North Beach"),
        DroneVideo(id: 13, caption: "New Office Site"),
        DroneVideo(id: 14, caption: "Bay to Breakers"),
        DroneVideo(id: 15, caption: "Wailea, Maui"),
        DroneVideo(id: 16, caption: "Hvar, Croatia"),
        DroneVideo(id: 17, caption: "Sather Tower, Berkeley"),
        DroneVideo(id: 18, caption: "Villa Collina"),
        DroneVideo(id: 19, caption: "Waves"),
        DroneVideo(id: 20, caption: "Venice Canals"),
        DroneVideo(id: 21, caption: "University of San Francisco"),
        DroneVideo(id: 22, caption: "Old Valencia, Spain"),
        DroneVideo(id: 23, caption: "Arches National Park"),
        DroneVideo(id: 24, caption: "Mont Saint-Michel, France"),
        DroneVideo(id: 26, caption: "Salzburg, Austria"),
        DroneVideo(id: 27, caption: "Park City Morning, Utah"),
        DroneVideo(id: 29, caption: "Canyonlands National Park"),
        DroneVideo(id: 30, caption: "Vogelsang Lake, Yosemite"),
        DroneVideo(id: 31, caption: "Austria"),
        DroneVideo(id: 32, caption: "Almaden Green"),
        DroneVideo(id: 33, caption: "Mont Saint-Michel"),
        DroneVideo(id: 34, caption: "SF Lunar New Year"),
        DroneVideo(id: 35, caption: "Big Sur Hills"),
        DroneVideo(id: 36, caption: "Fort Funston"),
        DroneVideo(id: 37, caption: "Fort Funston & Golden Gate"),
        DroneVideo(id: 39, caption: "Mont Saint-Michel"),
        DroneVideo(id: 40, caption: "Neuschwanstein Castle, Germany"),
        DroneVideo(id: 41, caption: "Park City, Utah"),
        DroneVideo(id: 42, caption: "Golden Gate Bridge"),
        DroneVideo(id: 43, caption: "Balearic Islands, Spain"),
        DroneVideo(id: 44, caption: "Mont Saint-Michel"),
        DroneVideo(id: 45, caption: "Drifting Away"),
        DroneVideo(id: 46, caption: "Laguna de los Tres, Patagonia"),
        DroneVideo(id: 47, caption: "Canyonlands"),
        DroneVideo(id: 48, caption: "Ka\u{02BB}anapali Surf, Maui"),
        DroneVideo(id: 49, caption: "Copacabana, Brazil"),
        DroneVideo(id: 50, caption: "Palma, Mallorca"),
        DroneVideo(id: 51, caption: "Fuschl am See, Austria"),
        DroneVideo(id: 52, caption: "Moab, Utah"),
        DroneVideo(id: 53, caption: "Carmel-by-the-Sea"),
        DroneVideo(id: 54, caption: "Garrapata State Park"),
        DroneVideo(id: 55, caption: "Arches National Park"),
        DroneVideo(id: 56, caption: "Wailea South, Maui"),
        DroneVideo(id: 57, caption: "Red Rocks"),
        DroneVideo(id: 58, caption: "Alviso Salt Marsh"),
        DroneVideo(id: 59, caption: "UC Berkeley Campus"),
        DroneVideo(id: 60, caption: "SF Embarcadero"),
        DroneVideo(id: 61, caption: "Stanford Main Quad"),
        DroneVideo(id: 62, caption: "Sather Tower, Berkeley"),
        DroneVideo(id: 63, caption: "Albanian Alps"),
        DroneVideo(id: 64, caption: "Kotor, Montenegro"),
        DroneVideo(id: 65, caption: "Deer Valley, Utah"),
        DroneVideo(id: 66, caption: "Denver, Colorado"),
        DroneVideo(id: 67, caption: "Dubrovnik, Croatia"),
        DroneVideo(id: 68, caption: "Grand Baths, Budapest"),
        DroneVideo(id: 69, caption: "Ho\u{02BB}okipa Beach, Maui"),
        DroneVideo(id: 70, caption: "Bay of Kotor, Montenegro"),
        DroneVideo(id: 71, caption: "Lands End, San Francisco"),
        DroneVideo(id: 72, caption: "Maui Lava Coast"),
        DroneVideo(id: 73, caption: "Ocean Beach, San Francisco"),
        DroneVideo(id: 74, caption: "Old Town Dubrovnik"),
        DroneVideo(id: 75, caption: "Port Novi, Montenegro"),
        DroneVideo(id: 76, caption: "Sch\u{00F6}nbrunn Palace, Vienna"),
        DroneVideo(id: 77, caption: "Theth, Albania at Sunset"),
        DroneVideo(id: 78, caption: "Theth Summit, Albania"),
        DroneVideo(id: 79, caption: "Theth Sunrise, Albania"),
        DroneVideo(id: 80, caption: "Tivat, Montenegro"),
        DroneVideo(id: 81, caption: "Walled City of Dubrovnik"),
        DroneVideo(id: 82, caption: "West Maui Coastline"),
        DroneVideo(id: 83, caption: "Yosemite Falls"),
        DroneVideo(id: 84, caption: "Yosemite Valley at Twilight"),
        DroneVideo(id: 85, caption: "Yosemite Valley"),
    ]

    static func shuffled() -> [DroneVideo] { all.shuffled() }
}
